### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.DoInDirectory#1]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by pitermarx** [comment]
Cool thks

**Comment by pitermarx** [comment]
It's in PR now

**Comment by gep13** [comment]
Thanks for doing this!

**Comment by pitermarx** [comment]
should it be live now?

**Comment by gep13** [comment]
No, not quite.  Just sent it to the develop website for final testing, and will then push to master website.

**Comment by pitermarx** [comment]
ok
