### ISSUE TITLE
Release version of Cake.DoInDirectory compatible with Cake v1.0

### ISSUE THREAD

**Issue by minoseah629** [cake-contrib/Cake.DoInDirectory#15]
is there any plans on updating to reference cake v1.0.0

https://www.nuget.org/packages/Cake

**Comment by pitermarx** [comment]
no plans. sorry. But I can accept a PR or even transfer ownership of the repo

**Comment by pitermarx** [comment]
I created a branch and just updated the versions. let's see if the build passes.
https://github.com/cake-contrib/Cake.DoInDirectory/pull/16
