### ISSUE TITLE
Update Cake.DoInDirectory add-in to target Cake v2.0.0

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.DoInDirectory#21]
[Cake 2.0.0](https://cakebuild.net/blog/2021/11/cake-v2.0.0-released) has been released  🎉

**Comment by paulmilbank** [comment]
Have added a PR for this now: https://github.com/cake-contrib/Cake.DoInDirectory/pull/23. I think the README and semver version may need to be updated to reflect the breaking change to dropping netstandard2.0 support

**Comment by augustoproiete** [comment]
Implemented via https://github.com/cake-contrib/Cake.DoInDirectory/pull/23

**Comment by augustoproiete** [comment]
:tada: The changes implemented in response to this issue shipped with **Cake.DoInDirectory v5.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/cake-contrib/Cake.DoInDirectory/releases/tag/5.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Cake.DoInDirectory/5.0.0)
