### ISSUE TITLE
Do In Directory build warning

### ISSUE THREAD

**Issue by minoseah629** [cake-contrib/Cake.DoInDirectory#22]
During a build, I see this warning. 

The assembly 'Cake.DoInDirectory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (1.0.0).
For best compatibility it should target Cake.Core version 2.0.0.

https://github.com/cake-contrib/Cake.DoInDirectory/blob/6cc8dc10ca24cd1af0c6ae15a63c34407c74abc7/Cake.DoInDirectory/Cake.DoInDirectory.csproj#L26

**Comment by augustoproiete** [comment]
Hey @minoseah629 this is expected until we [Update Cake.DoInDirectory add-in to target Cake v2.0.0](https://github.com/cake-contrib/Cake.DoInDirectory/issues/21)

Let me know if you'd like to send a PR for that one.

**Comment by augustoproiete** [comment]
@minoseah629

:tada: The changes implemented in response to this issue shipped with **Cake.DoInDirectory v5.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/cake-contrib/Cake.DoInDirectory/releases/tag/5.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Cake.DoInDirectory/5.0.0)
