### ISSUE TITLE
Target netstandard2.0 to run with Cake.CoreCLR

### ISSUE THREAD

**Issue by git-man** [cake-contrib/Cake.DoInDirectory#7]
It would be cool, if the Cake.CoreCLR compatibility could be added, as stated here:
https://cakebuild.net/blog/2018/02/cake-v0.26.0-released
Due to this only "netstandard2.0" needs to be targeted by the addin.

Thanks for your support and your great work!

**Comment by pitermarx** [comment]
Not really able to do it any time soon. But I'm open to contributions

**Comment by pitermarx** [comment]
Closed by #8

**Comment by pitermarx** [comment]
already on [nuget](https://www.nuget.org/packages/Cake.DoInDirectory/3.0.0). Thanks for the help
